# Generated by Django 2.2.3 on 2019-07-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_tag_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
