# Generated by Django 2.2.3 on 2019-07-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_auto_20190718_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='consumer.Province'),
        ),
    ]
